// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Meetup struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	User        *User  `json:"user"`
}

type NewMeetup struct {
	Name        string `json:"name"`
	UserID      string `json:"userId"`
	Description string `json:"description"`
}

type User struct {
	ID       string    `json:"id"`
	Username string    `json:"username"`
	Meetups  []*Meetup `json:"meetups"`
}
